### ISSUE TITLE
No such command

### ISSUE THREAD

**Issue by albertsgarde** [matbesancon/cargo-cite#4]
I've installed with
`cargo install cite`
I got the message that it has been successful, and when I try to install again, I get
```
$ cargo install cite
    Updating crates.io index
     Ignored package `cite v0.3.0` is already installed, use --force to override
```
but when I run
`cargo cite`
I get the message
```
error: no such subcommand: `cite`

        Did you mean `c`?
```
also `cite` does not come up when I run `cargo --list`.

What am I doing wrong?

**Comment by matbesancon** [comment]
Naive question but I'm not sure if this package is registered, so the line
```
 cargo install cite
```
might no be fetching this package

**Comment by albertsgarde** [comment]
That makes a lot of sense... haha

**Comment by albertsgarde** [comment]
After cloning the repo and running `cargo install --path .` I got it to work. First time I've had to do that, so maybe add installation instructions to readme? Might just be me.
